package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type Config struct {
	path string
	data map[string]string
}

func New(path string) *Config {
	return &Config{
		path: path,
		data: make(map[string]string),
	}
}

func NewUser() *Config {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	path := filepath.Join(home, ".config", "sketchybar", "user.sketchybarrc")
	return New(path)
}

func NewDefault() *Config {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	path := filepath.Join(home, ".config", "sketchybar", "sketchybarrc")
	return New(path)
}

func (c *Config) Load() error {
	file, err := os.Open(c.path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	defer file.Close()

	exportRegex := regexp.MustCompile(`^export\s+([A-Z_]+)=(.*)$`)
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if matches := exportRegex.FindStringSubmatch(line); matches != nil {
			key := matches[1]
			value := matches[2]
			value = strings.Trim(value, `"`)
			c.data[key] = value
		}
	}

	return scanner.Err()
}

func (c *Config) Get(key string) (string, bool) {
	val, ok := c.data[key]
	return val, ok
}

func (c *Config) Set(key, value string) {
	c.data[key] = value
}

func (c *Config) List() map[string]string {
	result := make(map[string]string)
	for k, v := range c.data {
		result[k] = v
	}
	return result
}

func (c *Config) Save() error {
	dir := filepath.Dir(c.path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	file, err := os.Create(c.path)
	if err != nil {
		return err
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	fmt.Fprintln(writer, "#!/usr/bin/env bash")
	fmt.Fprintln(writer, "")
	fmt.Fprintln(writer, "# User Custom Configuration")
	fmt.Fprintln(writer, "# Generated by gsbar")
	fmt.Fprintln(writer, "")

	for key, value := range c.data {
		if strings.Contains(value, " ") || !regexp.MustCompile(`^[a-zA-Z0-9_/.-]+$`).MatchString(value) {
			fmt.Fprintf(writer, "export %s=\"%s\"\n", key, value)
		} else {
			fmt.Fprintf(writer, "export %s=%s\n", key, value)
		}
	}

	return writer.Flush()
}

func GetValueCascade(key string) (string, error) {
	userCfg := NewUser()
	if userCfg == nil {
		return "", fmt.Errorf("failed to get user config path")
	}

	if err := userCfg.Load(); err != nil {
		return "", err
	}

	if val, ok := userCfg.Get(key); ok {
		return val, nil
	}

	defaultCfg := NewDefault()
	if defaultCfg == nil {
		return "", fmt.Errorf("failed to get default config path")
	}

	if err := defaultCfg.Load(); err != nil {
		return "", err
	}

	if val, ok := defaultCfg.Get(key); ok {
		return val, nil
	}

	return "", fmt.Errorf("key not found: %s", key)
}
